<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="io.pleo.antaeus.rest.AntaeusRestTest" tests="9" skipped="0" failures="0" errors="0" timestamp="2023-12-26T22:35:55" hostname="Szymons-MBP.technicolor.net" time="0.969">
  <properties/>
  <testcase name="should GET customer by id()" classname="io.pleo.antaeus.rest.AntaeusRestTest" time="0.738"/>
  <testcase name="should GET healthcheck message()" classname="io.pleo.antaeus.rest.AntaeusRestTest" time="0.008"/>
  <testcase name="should return 404 when invoice does not exist()" classname="io.pleo.antaeus.rest.AntaeusRestTest" time="0.015"/>
  <testcase name="should GET invoice by id()" classname="io.pleo.antaeus.rest.AntaeusRestTest" time="0.026"/>
  <testcase name="should return 400 when charging invoice with incompatible currency()" classname="io.pleo.antaeus.rest.AntaeusRestTest" time="0.016"/>
  <testcase name="should GET all invoices()" classname="io.pleo.antaeus.rest.AntaeusRestTest" time="0.13"/>
  <testcase name="should charge invoice by id()" classname="io.pleo.antaeus.rest.AntaeusRestTest" time="0.012"/>
  <testcase name="should GET all customers()" classname="io.pleo.antaeus.rest.AntaeusRestTest" time="0.011"/>
  <testcase name="should return 404 when customer does not exist()" classname="io.pleo.antaeus.rest.AntaeusRestTest" time="0.01"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
